### ISSUE TITLE
Backups path

### ISSUE THREAD

**Issue by obazoud** [hw-cookbooks/chef-server-populator#21]
Is it work with Chef 12 ?
https://github.com/hw-cookbooks/chef-server-populator/blob/master/recipes/backups.rb#L59

Should be:
```
cron 'Chef Server Backups' do
...
  path "$PATH:/opt/opscode/embedded/bin/"
end
```

**Comment by cwjohnston** [comment]
Hi Oliver,

We have tested this with Chef Server 12 and found it to work. Here's a little background on the logic.

In the `backups` recipe we use the `gem_package` resource to install gem dependencies defined in the `node[:chef_server_populator][:backup_gems]` attribute hash. Based on the behavior of `gem_package` we expect that chef-client should install the gems into either a) a system ruby detected in the path, or b) the chef-client embedded ruby in `/opt/chef/embedded/bin`. 

Because chef-client is unaware of the Chef Server embedded ruby, the gem dependencies for backups won't be installed there, making it unsuitable to append `/opt/opscode/embedded/bin` to the cron path instead of `/opt/chef/embedded/bin`.

**Comment by luckymike** [comment]
As Cameron indicated, we want to use the chef-client embedded ruby. However, we've addressed some issues with the backup script in version 1.2.0, that may resolve the problem that triggered this issue.
